Fix: missing 1 required positional argument: 'server'
The complete error message is:
TypeError: CozytouchClient.__init__() missing 1 required positional argument: 'server'

Closes: https://github.com/Cyr-ius/cozytouchpy/issues/15